version: '3.8'
services:
  api:
    build: .
    container_name: eco2_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "until npx prisma migrate deploy; do echo 'Esperando a que Neon despierte...'; sleep 3; done && npm run dev"