import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaPg({ connectionString })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log("🌱 Seeding ECO2 database...")

  // =====================
  // ACHIEVEMENTS
  // =====================
  console.log("🏆 Seeding achievements...")

  const achievements = [
    {
      name: "Primeros Pasos",
      description: "Completa el onboarding de ECO2",
      condition_type: "onboarding_completed",
      condition_value: 1,
      xp_reward: 50,
      seed_reward: 10,
    },
    {
      name: "Ojo Botánico",
      description: "Escanea tu primera planta con IA",
      condition_type: "plant_scans",
      condition_value: 1,
      xp_reward: 100,
      seed_reward: 15,
    },
    {
      name: "Mi Primer Espacio",
      description: "Crea tu primera habitación",
      condition_type: "rooms_created",
      condition_value: 1,
      xp_reward: 100,
      seed_reward: 15,
    },
    {
      name: "Manos a la Obra",
      description: "Realiza tu primer cuidado",
      condition_type: "care_logs",
      condition_value: 1,
      xp_reward: 50,
      seed_reward: 10,
    },
    {
      name: "Cuidador Constante",
      description: "Realiza 10 cuidados",
      condition_type: "care_logs",
      condition_value: 10,
      xp_reward: 200,
      seed_reward: 30,
    },
    {
      name: "Guardián Verde",
      description: "Realiza 30 cuidados",
      condition_type: "care_logs",
      condition_value: 30,
      xp_reward: 500,
      seed_reward: 75,
    },
    {
      name: "Maestro del Cuidado",
      description: "Realiza 50 cuidados",
      condition_type: "care_logs",
      condition_value: 50,
      xp_reward: 1500,
      seed_reward: 200,
    },
    {
      name: "Leyenda Botánica",
      description: "Realiza 100 cuidados",
      condition_type: "care_logs",
      condition_value: 100,
      xp_reward: 3000,
      seed_reward: 400,
    },
    {
      name: "Mi Pequeño Jardín",
      description: "Registra 3 plantas en tu colección",
      condition_type: "user_plants",
      condition_value: 3,
      xp_reward: 200,
      seed_reward: 30,
    },
    {
      name: "Coleccionista",
      description: "Registra 5 plantas en tu colección",
      condition_type: "user_plants",
      condition_value: 5,
      xp_reward: 1000,
      seed_reward: 150,
    },
  ]

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { name: achievement.name },
      update: achievement,
      create: achievement,
    })
  }

  console.log(`✅ ${achievements.length} achievements seeded`)

  // =====================
  // PLANT SPECIES
  // =====================
  console.log("🌿 Seeding plant species...")

  const species = [
    // TROPICALES
    {
      scientific_name: "Epipremnum aureum",
      common_name: "Pothos / Potos",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 15,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009302/pothos_tv2khr.jpg",
    },
    {
      scientific_name: "Monstera deliciosa",
      common_name: "Monstera / Costilla de Adán",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 18,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009311/monstera_costilla_de_adan_qbks58.jpg",
    },
    {
      scientific_name: "Monstera adansonii",
      common_name: "Monstera Suizo / Queso",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "high",
      air_purification_score: 6,
      min_temperature: 18,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009312/monstera_suizo_lfq09c.jpg",
    },
    {
      scientific_name: "Philodendron hederaceum",
      common_name: "Filodendro Corazón",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 7,
      min_temperature: 16,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009297/filodendro_corazon_qozwzv.jpg",
    },
    {
      scientific_name: "Philodendron bipinnatifidum",
      common_name: "Filodendro Árbol",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 18,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009306/filodendro_arbol_ukffwz.jpg",
    },
    {
      scientific_name: "Spathiphyllum wallisii",
      common_name: "Cuna de Moisés / Lirio de Paz",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 9,
      min_temperature: 18,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009293/cuna_de_moises_l2pz1t.jpg",
    },
    {
      scientific_name: "Aglaonema commutatum",
      common_name: "Aglaonema / Chinese Evergreen",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 16,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009287/Aglaonema_q2utbx.jpg",
    },
    {
      scientific_name: "Dieffenbachia seguine",
      common_name: "Diefenbaquia / Lotería",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 6,
      min_temperature: 18,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009294/diefenbaquia_pismyc.jpg",
    },
    {
      scientific_name: "Anthurium andraeanum",
      common_name: "Anturio / Flor de Cera",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 18,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009288/anthurium_andraeanum_czy0ui.jpg",
    },
    {
      scientific_name: "Calathea ornata",
      common_name: "Calatea Ornata / Planta Pavo Real",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 18,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009291/calatea_ornata_qjuipm.jpg",
    },
    {
      scientific_name: "Calathea medallion",
      common_name: "Calatea Medallón",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 18,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009290/calatea_de_medallon_ufcgf1.jpg",
    },
    {
      scientific_name: "Maranta leuconeura",
      common_name: "Maranta / Planta Rezadora",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 16,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009311/maranta_lujnmj.jpg",
    },
    {
      scientific_name: "Tradescantia zebrina",
      common_name: "Tradescantia / Amor de Hombre",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "medium",
      air_purification_score: 4,
      min_temperature: 10,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009304/trasdencantia_sbimmr.jpg",
    },
    {
      scientific_name: "Ficus elastica",
      common_name: "Ficus Elastica / Caucho",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 16,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009296/ficus_elastica_m8iuqm.jpg",
    },
    {
      scientific_name: "Ficus lyrata",
      common_name: "Ficus Lyrata / Ficus Violín",
      category: "tropical",
      light_requirement: "high",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 7,
      min_temperature: 16,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009297/ficus_lyrata_nx7o4m.jpg",
    },
    {
      scientific_name: "Dracaena trifasciata",
      common_name: "Sanseveria / Lengua de Suegra",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 9,
      min_temperature: 10,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009305/sanseveria_hcllf1.jpg",
    },
    {
      scientific_name: "Dracaena marginata",
      common_name: "Dracena Marginata / Palma de Madagascar",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "low",
      air_purification_score: 8,
      min_temperature: 15,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009295/dracena_marginata_aoappz.jpg",
    },
    {
      scientific_name: "Dracaena fragrans",
      common_name: "Dracena Fragrans / Palo de Brasil",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 15,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009294/dracena_fragrans_wpjgov.jpg",
    },
    {
      scientific_name: "Zamioculcas zamiifolia",
      common_name: "ZZ Plant / Planta Eternity",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 7,
      min_temperature: 15,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009286/zz_plant_pfranr.jpg",
    },
    {
      scientific_name: "Chlorophytum comosum",
      common_name: "Cinta / Malamadre / Spider Plant",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 9,
      min_temperature: 10,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009298/malamadre_qfw59y.jpg",
    },
    {
      scientific_name: "Hedera helix",
      common_name: "Hiedra / Ivy",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 5,
      max_temperature: 28,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009309/hiedra_ktyhlm.jpg",
    },
    {
      scientific_name: "Schefflera actinophylla",
      common_name: "Schefflera / Paragüitas",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 7,
      min_temperature: 15,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009300/paraguitas_zimygd.jpg",
    },
    {
      scientific_name: "Syngonium podophyllum",
      common_name: "Singonio / Pata de Ganso",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 16,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009303/singonio_dj7tab.jpg",
    },
    {
      scientific_name: "Croton variegatum",
      common_name: "Crotón / Planta de Colores",
      category: "tropical",
      light_requirement: "high",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 18,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009293/croton_qdqg5e.jpg",
    },
    {
      scientific_name: "Colocasia esculenta",
      common_name: "Colocasia / Yautía Ornamental",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 4,
      min_temperature: 18,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009292/colocasia_gozywg.jpg",
    },
    // SUCULENTAS
    {
      scientific_name: "Aloe vera",
      common_name: "Sábila / Aloe Vera",
      category: "succulent",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 7,
      min_temperature: 10,
      max_temperature: 40,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009303/sabila_wd6rut.jpg",
    },
    {
      scientific_name: "Haworthiopsis attenuata",
      common_name: "Haworthia / Suculenta Cebra",
      category: "succulent",
      light_requirement: "indirect",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 3,
      min_temperature: 10,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009308/haworthia_iiiuxk.jpg",
    },
    {
      scientific_name: "Echeveria elegans",
      common_name: "Echeveria / Rosa de Piedra",
      category: "succulent",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 2,
      min_temperature: 8,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009295/echeveria_lv9lx2.jpg",
    },
    {
      scientific_name: "Sedum morganianum",
      common_name: "Cola de Burro / Sedum",
      category: "succulent",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 2,
      min_temperature: 10,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009292/cola_de_burro_jnxdeo.jpg",
    },
    {
      scientific_name: "Crassula ovata",
      common_name: "Árbol de Jade / Planta de Dinero",
      category: "succulent",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 4,
      min_temperature: 10,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009289/arbol_de_jade_ituwny.jpg",
    },
    // CACTUS
    {
      scientific_name: "Cereus repandus",
      common_name: "Cactus Columnar / Cardón",
      category: "cactus",
      light_requirement: "high",
      water_frequency_days: 21,
      humidity_preference: "low",
      air_purification_score: 2,
      min_temperature: 10,
      max_temperature: 40,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009291/cereus_repandus_emxi7l.jpg",
    },
    {
      scientific_name: "Opuntia microdasys",
      common_name: "Nopal / Tuna de Orejas",
      category: "cactus",
      light_requirement: "high",
      water_frequency_days: 21,
      humidity_preference: "low",
      air_purification_score: 2,
      min_temperature: 5,
      max_temperature: 40,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009314/nopal_r8q3d2.jpg",
    },
    {
      scientific_name: "Schlumbergera truncata",
      common_name: "Cactus de Navidad",
      category: "cactus",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 3,
      min_temperature: 10,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009290/cactus_de_navidad_qxogg7.jpg",
    },
    // HELECHOS
    {
      scientific_name: "Nephrolepis exaltata",
      common_name: "Helecho Boston / Helecho Espada",
      category: "fern",
      light_requirement: "indirect",
      water_frequency_days: 3,
      humidity_preference: "high",
      air_purification_score: 9,
      min_temperature: 15,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009307/helecho_de_boston_vsweqt.jpg",
    },
    {
      scientific_name: "Asplenium nidus",
      common_name: "Helecho Nido de Pájaro",
      category: "fern",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 18,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009308/helecho_nido_de_pajaro_qwfmg0.jpg",
    },
    // PLANTAS CON FLORES
    {
      scientific_name: "Hibiscus rosa-sinensis",
      common_name: "Amapola / Hibisco",
      category: "flowering",
      light_requirement: "high",
      water_frequency_days: 3,
      humidity_preference: "medium",
      air_purification_score: 4,
      min_temperature: 18,
      max_temperature: 38,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009287/Amapola_c6gltq.jpg",
    },
    {
      scientific_name: "Gardenia jasminoides",
      common_name: "Gardenia",
      category: "flowering",
      light_requirement: "high",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 16,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009307/gardenia_gcj23w.jpg",
    },
    {
      scientific_name: "Impatiens walleriana",
      common_name: "Miramelinda / Impatiens",
      category: "flowering",
      light_requirement: "indirect",
      water_frequency_days: 3,
      humidity_preference: "medium",
      air_purification_score: 3,
      min_temperature: 15,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009310/miarmelinda_seulvk.jpg",
    },
    {
      scientific_name: "Plumeria rubra",
      common_name: "Trinitaria / Frangipani",
      category: "flowering",
      light_requirement: "high",
      water_frequency_days: 7,
      humidity_preference: "low",
      air_purification_score: 3,
      min_temperature: 18,
      max_temperature: 38,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009305/trinitaria_fk6shu.jpg",
    },
    // HIERBAS
    {
      scientific_name: "Ocimum basilicum",
      common_name: "Albahaca",
      category: "herb",
      light_requirement: "high",
      water_frequency_days: 2,
      humidity_preference: "medium",
      air_purification_score: 3,
      min_temperature: 15,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009287/albahaca_jkh7cr.jpg",
    },
    {
      scientific_name: "Mentha spicata",
      common_name: "Yerba Buena / Menta",
      category: "herb",
      light_requirement: "high",
      water_frequency_days: 2,
      humidity_preference: "high",
      air_purification_score: 3,
      min_temperature: 10,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009305/yerba_buena_tvra39.jpg",
    },
    {
      scientific_name: "Rosmarinus officinalis",
      common_name: "Romero",
      category: "herb",
      light_requirement: "high",
      water_frequency_days: 7,
      humidity_preference: "low",
      air_purification_score: 4,
      min_temperature: 5,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009302/romero_czdq1e.jpg",
    },
    {
      scientific_name: "Aloe barbadensis",
      common_name: "Sábila de Barbados",
      category: "herb",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 6,
      min_temperature: 10,
      max_temperature: 40,
      // Sin image_url — no vino en el export manual; falta cargarla.
    },
    // ÁRBOLES DE INTERIOR
    {
      scientific_name: "Pachira aquatica",
      common_name: "Árbol del Dinero / Money Tree",
      category: "tree",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 6,
      min_temperature: 16,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009288/arbol_del_dinero_tljrbw.jpg",
    },
    {
      scientific_name: "Beaucarnea recurvata",
      common_name: "Pata de Elefante / Nolina",
      category: "tree",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 4,
      min_temperature: 10,
      max_temperature: 38,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009301/pata_de_elefante_bz8sne.jpg",
    },
    {
      scientific_name: "Chrysalidocarpus lutescens",
      common_name: "Palma Areca / Palma Bambú",
      category: "tree",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 9,
      min_temperature: 16,
      max_temperature: 35,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009313/palma_areca_ta0bt8.jpg",
    },
    {
      scientific_name: "Howea forsteriana",
      common_name: "Palma Kentia",
      category: "tree",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 12,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009300/palma_kentia_iikgkk.jpg",
    },
    {
      scientific_name: "Rhapis excelsa",
      common_name: "Palma Dama / Lady Palm",
      category: "tree",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 10,
      max_temperature: 32,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009299/palma_dama_pefwvr.jpg",
    },
    // OTRAS
    {
      scientific_name: "Bromelia fastuosa",
      common_name: "Bromelia / Piña Ornamental",
      category: "other",
      light_requirement: "high",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 5,
      min_temperature: 18,
      max_temperature: 38,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009289/bromelia_fastuosa_lcvqwt.jpg",
    },
    {
      scientific_name: "Peperomia obtusifolia",
      common_name: "Peperomia / Baby Rubber Plant",
      category: "other",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 5,
      min_temperature: 15,
      max_temperature: 30,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009302/peperomia_lerb0p.jpg",
    },
    {
      scientific_name: "Oxalis triangularis",
      common_name: "Trébol Morado / False Shamrock",
      category: "other",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 3,
      min_temperature: 10,
      max_temperature: 28,
      image_url: "https://res.cloudinary.com/dokdkdwvl/image/upload/v1788009304/trebol_morado_ddxebh.jpg",
    },
  ]

  for (const plant of species) {
    await prisma.plantSpecies.upsert({
      where: { scientific_name: plant.scientific_name },
      update: plant as any,
      create: plant as any,
    })
  }

  console.log(`✅ ${species.length} plant species seeded`)
  console.log("🎉 Seed completed successfully!")
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })