import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaPg({ connectionString })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log("🌱 Seeding ECO2 database...")

  // =====================
  // ACHIEVEMENTS
  // =====================
  console.log("🏆 Seeding achievements...")

  const achievements = [
    {
      name: "Primeros Pasos",
      description: "Completa el onboarding de ECO2",
      condition_type: "onboarding_completed",
      condition_value: 1,
      xp_reward: 50,
    },
    {
      name: "Ojo Botánico",
      description: "Escanea tu primera planta con IA",
      condition_type: "plant_scans",
      condition_value: 1,
      xp_reward: 100,
    },
    {
      name: "Mi Primer Espacio",
      description: "Crea tu primera habitación",
      condition_type: "rooms_created",
      condition_value: 1,
      xp_reward: 100,
    },
    {
      name: "Manos a la Obra",
      description: "Realiza tu primer cuidado",
      condition_type: "care_logs",
      condition_value: 1,
      xp_reward: 50,
    },
    {
      name: "Cuidador Constante",
      description: "Realiza 10 cuidados",
      condition_type: "care_logs",
      condition_value: 10,
      xp_reward: 200,
    },
    {
      name: "Guardián Verde",
      description: "Realiza 30 cuidados",
      condition_type: "care_logs",
      condition_value: 30,
      xp_reward: 500,
    },
    {
      name: "Maestro del Cuidado",
      description: "Realiza 50 cuidados",
      condition_type: "care_logs",
      condition_value: 50,
      xp_reward: 1500,
    },
    {
      name: "Leyenda Botánica",
      description: "Realiza 100 cuidados",
      condition_type: "care_logs",
      condition_value: 100,
      xp_reward: 3000,
    },
    {
      name: "Mi Pequeño Jardín",
      description: "Registra 3 plantas en tu colección",
      condition_type: "user_plants",
      condition_value: 3,
      xp_reward: 200,
    },
    {
      name: "Coleccionista",
      description: "Registra 5 plantas en tu colección",
      condition_type: "user_plants",
      condition_value: 5,
      xp_reward: 1000,
    },
  ]

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { name: achievement.name },
      update: achievement,
      create: achievement,
    })
  }

  console.log(`✅ ${achievements.length} achievements seeded`)

  // =====================
  // PLANT SPECIES
  // =====================
  console.log("🌿 Seeding plant species...")

  const species = [
    // TROPICALES
    {
      scientific_name: "Epipremnum aureum",
      common_name: "Pothos / Potos",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 15,
      max_temperature: 35,
    },
    {
      scientific_name: "Monstera deliciosa",
      common_name: "Monstera / Costilla de Adán",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 18,
      max_temperature: 30,
    },
    {
      scientific_name: "Monstera adansonii",
      common_name: "Monstera Suizo / Queso",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "high",
      air_purification_score: 6,
      min_temperature: 18,
      max_temperature: 30,
    },
    {
      scientific_name: "Philodendron hederaceum",
      common_name: "Filodendro Corazón",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 7,
      min_temperature: 16,
      max_temperature: 32,
    },
    {
      scientific_name: "Philodendron bipinnatifidum",
      common_name: "Filodendro Árbol",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 18,
      max_temperature: 32,
    },
    {
      scientific_name: "Spathiphyllum wallisii",
      common_name: "Cuna de Moisés / Lirio de Paz",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 9,
      min_temperature: 18,
      max_temperature: 30,
    },
    {
      scientific_name: "Aglaonema commutatum",
      common_name: "Aglaonema / Chinese Evergreen",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 16,
      max_temperature: 32,
    },
    {
      scientific_name: "Dieffenbachia seguine",
      common_name: "Diefenbaquia / Lotería",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 6,
      min_temperature: 18,
      max_temperature: 32,
    },
    {
      scientific_name: "Anthurium andraeanum",
      common_name: "Anturio / Flor de Cera",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 18,
      max_temperature: 30,
    },
    {
      scientific_name: "Calathea ornata",
      common_name: "Calatea Ornata / Planta Pavo Real",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 18,
      max_temperature: 30,
    },
    {
      scientific_name: "Calathea medallion",
      common_name: "Calatea Medallón",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 18,
      max_temperature: 30,
    },
    {
      scientific_name: "Maranta leuconeura",
      common_name: "Maranta / Planta Rezadora",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 16,
      max_temperature: 30,
    },
    {
      scientific_name: "Tradescantia zebrina",
      common_name: "Tradescantia / Amor de Hombre",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "medium",
      air_purification_score: 4,
      min_temperature: 10,
      max_temperature: 32,
    },
    {
      scientific_name: "Ficus elastica",
      common_name: "Ficus Elastica / Caucho",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 16,
      max_temperature: 32,
    },
    {
      scientific_name: "Ficus lyrata",
      common_name: "Ficus Lyrata / Ficus Violín",
      category: "tropical",
      light_requirement: "high",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 7,
      min_temperature: 16,
      max_temperature: 30,
    },
    {
      scientific_name: "Dracaena trifasciata",
      common_name: "Sanseveria / Lengua de Suegra",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 9,
      min_temperature: 10,
      max_temperature: 35,
    },
    {
      scientific_name: "Dracaena marginata",
      common_name: "Dracena Marginata / Palma de Madagascar",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "low",
      air_purification_score: 8,
      min_temperature: 15,
      max_temperature: 32,
    },
    {
      scientific_name: "Dracaena fragrans",
      common_name: "Dracena Fragrans / Palo de Brasil",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 15,
      max_temperature: 32,
    },
    {
      scientific_name: "Zamioculcas zamiifolia",
      common_name: "ZZ Plant / Planta Eternity",
      category: "tropical",
      light_requirement: "low",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 7,
      min_temperature: 15,
      max_temperature: 35,
    },
    {
      scientific_name: "Chlorophytum comosum",
      common_name: "Cinta / Malamadre / Spider Plant",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 9,
      min_temperature: 10,
      max_temperature: 32,
    },
    {
      scientific_name: "Hedera helix",
      common_name: "Hiedra / Ivy",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 5,
      max_temperature: 28,
    },
    {
      scientific_name: "Schefflera actinophylla",
      common_name: "Schefflera / Paragüitas",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 7,
      min_temperature: 15,
      max_temperature: 32,
    },
    {
      scientific_name: "Syngonium podophyllum",
      common_name: "Singonio / Pata de Ganso",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 16,
      max_temperature: 32,
    },
    {
      scientific_name: "Croton variegatum",
      common_name: "Crotón / Planta de Colores",
      category: "tropical",
      light_requirement: "high",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 18,
      max_temperature: 35,
    },
    {
      scientific_name: "Colocasia esculenta",
      common_name: "Colocasia / Yautía Ornamental",
      category: "tropical",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 4,
      min_temperature: 18,
      max_temperature: 35,
    },
    // SUCULENTAS
    {
      scientific_name: "Aloe vera",
      common_name: "Sábila / Aloe Vera",
      category: "succulent",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 7,
      min_temperature: 10,
      max_temperature: 40,
    },
    {
      scientific_name: "Haworthiopsis attenuata",
      common_name: "Haworthia / Suculenta Cebra",
      category: "succulent",
      light_requirement: "indirect",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 3,
      min_temperature: 10,
      max_temperature: 35,
    },
    {
      scientific_name: "Echeveria elegans",
      common_name: "Echeveria / Rosa de Piedra",
      category: "succulent",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 2,
      min_temperature: 8,
      max_temperature: 35,
    },
    {
      scientific_name: "Sedum morganianum",
      common_name: "Cola de Burro / Sedum",
      category: "succulent",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 2,
      min_temperature: 10,
      max_temperature: 35,
    },
    {
      scientific_name: "Crassula ovata",
      common_name: "Árbol de Jade / Planta de Dinero",
      category: "succulent",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 4,
      min_temperature: 10,
      max_temperature: 35,
    },
    // CACTUS
    {
      scientific_name: "Cereus repandus",
      common_name: "Cactus Columnar / Cardón",
      category: "cactus",
      light_requirement: "high",
      water_frequency_days: 21,
      humidity_preference: "low",
      air_purification_score: 2,
      min_temperature: 10,
      max_temperature: 40,
    },
    {
      scientific_name: "Opuntia microdasys",
      common_name: "Nopal / Tuna de Orejas",
      category: "cactus",
      light_requirement: "high",
      water_frequency_days: 21,
      humidity_preference: "low",
      air_purification_score: 2,
      min_temperature: 5,
      max_temperature: 40,
    },
    {
      scientific_name: "Schlumbergera truncata",
      common_name: "Cactus de Navidad",
      category: "cactus",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 3,
      min_temperature: 10,
      max_temperature: 30,
    },
    // HELECHOS
    {
      scientific_name: "Nephrolepis exaltata",
      common_name: "Helecho Boston / Helecho Espada",
      category: "fern",
      light_requirement: "indirect",
      water_frequency_days: 3,
      humidity_preference: "high",
      air_purification_score: 9,
      min_temperature: 15,
      max_temperature: 30,
    },
    {
      scientific_name: "Asplenium nidus",
      common_name: "Helecho Nido de Pájaro",
      category: "fern",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 7,
      min_temperature: 18,
      max_temperature: 30,
    },
    // PLANTAS CON FLORES
    {
      scientific_name: "Hibiscus rosa-sinensis",
      common_name: "Amapola / Hibisco",
      category: "flowering",
      light_requirement: "high",
      water_frequency_days: 3,
      humidity_preference: "medium",
      air_purification_score: 4,
      min_temperature: 18,
      max_temperature: 38,
    },
    {
      scientific_name: "Gardenia jasminoides",
      common_name: "Gardenia",
      category: "flowering",
      light_requirement: "high",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 5,
      min_temperature: 16,
      max_temperature: 30,
    },
    {
      scientific_name: "Impatiens walleriana",
      common_name: "Miramelinda / Impatiens",
      category: "flowering",
      light_requirement: "indirect",
      water_frequency_days: 3,
      humidity_preference: "medium",
      air_purification_score: 3,
      min_temperature: 15,
      max_temperature: 30,
    },
    {
      scientific_name: "Plumeria rubra",
      common_name: "Trinitaria / Frangipani",
      category: "flowering",
      light_requirement: "high",
      water_frequency_days: 7,
      humidity_preference: "low",
      air_purification_score: 3,
      min_temperature: 18,
      max_temperature: 38,
    },
    // HIERBAS
    {
      scientific_name: "Ocimum basilicum",
      common_name: "Albahaca",
      category: "herb",
      light_requirement: "high",
      water_frequency_days: 2,
      humidity_preference: "medium",
      air_purification_score: 3,
      min_temperature: 15,
      max_temperature: 35,
    },
    {
      scientific_name: "Mentha spicata",
      common_name: "Yerba Buena / Menta",
      category: "herb",
      light_requirement: "high",
      water_frequency_days: 2,
      humidity_preference: "high",
      air_purification_score: 3,
      min_temperature: 10,
      max_temperature: 30,
    },
    {
      scientific_name: "Rosmarinus officinalis",
      common_name: "Romero",
      category: "herb",
      light_requirement: "high",
      water_frequency_days: 7,
      humidity_preference: "low",
      air_purification_score: 4,
      min_temperature: 5,
      max_temperature: 35,
    },
    {
      scientific_name: "Aloe barbadensis",
      common_name: "Sábila de Barbados",
      category: "herb",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 6,
      min_temperature: 10,
      max_temperature: 40,
    },
    // ÁRBOLES DE INTERIOR
    {
      scientific_name: "Pachira aquatica",
      common_name: "Árbol del Dinero / Money Tree",
      category: "tree",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 6,
      min_temperature: 16,
      max_temperature: 35,
    },
    {
      scientific_name: "Beaucarnea recurvata",
      common_name: "Pata de Elefante / Nolina",
      category: "tree",
      light_requirement: "high",
      water_frequency_days: 14,
      humidity_preference: "low",
      air_purification_score: 4,
      min_temperature: 10,
      max_temperature: 38,
    },
    {
      scientific_name: "Chrysalidocarpus lutescens",
      common_name: "Palma Areca / Palma Bambú",
      category: "tree",
      light_requirement: "indirect",
      water_frequency_days: 5,
      humidity_preference: "high",
      air_purification_score: 9,
      min_temperature: 16,
      max_temperature: 35,
    },
    {
      scientific_name: "Howea forsteriana",
      common_name: "Palma Kentia",
      category: "tree",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 12,
      max_temperature: 30,
    },
    {
      scientific_name: "Rhapis excelsa",
      common_name: "Palma Dama / Lady Palm",
      category: "tree",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 8,
      min_temperature: 10,
      max_temperature: 32,
    },
    // OTRAS
    {
      scientific_name: "Bromelia fastuosa",
      common_name: "Bromelia / Piña Ornamental",
      category: "other",
      light_requirement: "high",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 5,
      min_temperature: 18,
      max_temperature: 38,
    },
    {
      scientific_name: "Peperomia obtusifolia",
      common_name: "Peperomia / Baby Rubber Plant",
      category: "other",
      light_requirement: "indirect",
      water_frequency_days: 10,
      humidity_preference: "medium",
      air_purification_score: 5,
      min_temperature: 15,
      max_temperature: 30,
    },
    {
      scientific_name: "Oxalis triangularis",
      common_name: "Trébol Morado / False Shamrock",
      category: "other",
      light_requirement: "indirect",
      water_frequency_days: 7,
      humidity_preference: "medium",
      air_purification_score: 3,
      min_temperature: 10,
      max_temperature: 28,
    },
  ]

  for (const plant of species) {
    await prisma.plantSpecies.upsert({
      where: { scientific_name: plant.scientific_name },
      update: plant as any,
      create: plant as any,
    })
  }

  console.log(`✅ ${species.length} plant species seeded`)
  console.log("🎉 Seed completed successfully!")
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })